### ISSUE TITLE
module 'zalgo_text.zalgo' has no attribute 'zalgofy'

### ISSUE THREAD

**Issue by Amethyst93** [gregoryneal/zalgo#1]
installed on python 3.5 and 3.6 on Windows 10 via

`python -m pip install zalgo_text`.

Then created a python file like in your example:

`
from zalgo_text import zalgo
print(zalgo.zalgofy("Some text to zalgofy!"))
`

Gives error:

`
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    print(zalgo.zalgofy("Some text to zalgofy!"))
AttributeError: module 'zalgo_text.zalgo' has no attribute 'zalgofy'
`

Happens both on 3.5 and 3.6

Edit:

the `__init__.py` file is empty.

**Comment by gregoryneal** [comment]
Hi, let me take a look in a few hours after I get off work.

**Comment by gregoryneal** [comment]
Hi, so try to run:

`print(zalgo.zalgo.zalgofy('Some text to zalgofy!'))`

and report back your success if any.

**Comment by Amethyst93** [comment]
okay, so this is what I get now with the new line:

`TypeError: zalgofy() missing 1 required positional argument: 'text'`

**Comment by gregoryneal** [comment]
Okay I have recreated your issue and believe I have figured it out, try 

`print(zalgo.zalgo().zalgofy('Some text to zalgofy!'))`

We were not creating the zalgo class instance in the code 🤣

**Comment by Amethyst93** [comment]
W̠̮͖o̵̩͝r̄̎͜ķ̷ͥi̎̍͡ņ̆̽gͣ̎̀!̨̛̕ ċ̊͢:̧̏͢
